tasks:
  - name: Backend & Ollama Setup
    init: |
      # Install Node.js
      curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      sudo apt-get update && sudo apt-get install -y nodejs

      # Navigate to backend and install dependencies
      cd backend
      npm install > /workspace/brainstormer/npm_install_log.txt 2>&1
      echo "Backend npm install completed. Check npm_install_log.txt for full output."

      # Fix index.js for bakllava model (using sed for automation)
      sed -i 's/model: "llava-llama3",/model: "bakllava",/' index.js

      # Return to root for next task
      cd ..
    command: |
      # Start Ollama server in background, redirecting output to a dedicated log file
      # (Ollama will need to be installed/pulled manually first)
      echo "Attempting to start Ollama server..."
      # Assuming ollama is in PATH or specify /usr/local/bin/ollama if manually installed there
      # Using a generic 'ollama' here, as it might be in PATH after manual install.
      # If not, you'll use the specific path from manual installation.
      nohup ollama serve > /workspace/brainstormer/ollama_serve_log.txt 2>&1 &
      echo "Ollama server startup command issued. Check ollama_serve_log.txt for output."

      # Start Backend server in background, redirecting output to a dedicated log file
      cd backend
      echo "Attempting to start Backend server..."
      nohup node index.js > /workspace/brainstormer/backend_server_log.txt 2>&1 &
      echo "Backend server startup command issued. Check backend_server_log.txt for output."

      echo "Backend and Ollama startup commands issued. Now starting Frontend..."
