
tasks:
  - name: Backend & Ollama Setup
    init: |
      # Install Node.js
      curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      sudo apt-get update && sudo apt-get install -y nodejs

      # Find Ollama executable path and export it
      # Gitpod's 'workspace-full' often provides Ollama via Nix, but its path
      # needs to be found dynamically.
      OLLAMA_BIN=$(find /nix/store -name ollama -type f -executable 2>/dev/null | head -n 1)
      if [ -z "$OLLAMA_BIN" ]; then
        echo "ERROR: Ollama executable not found after searching Nix store."
        exit 1
      fi
      export OLLAMA_BIN
      echo "Ollama executable found at: $OLLAMA_BIN"

      # Pull bakllava model using the found path
      "$OLLAMA_BIN" pull bakllava

      # Navigate to backend and install dependencies
      cd backend
      npm install

      # Fix index.js for bakllava model (using sed for automation)
      sed -i 's/model: "llava-llama3",/model: "bakllava",/' index.js

      # Return to root for next task
      cd ..
    command: |
      # The OLLAMA_BIN variable is exported from init to command context
      # Start Ollama server in background
      nohup "$OLLAMA_BIN" serve &

      # Start Backend server in background
      cd backend
      nohup node index.js &

      echo "Backend and Ollama started. Now starting Frontend..."

  - name: Frontend Setup & Start
    init: |
      # Navigate to frontend and install dependencies
      cd frontend
      # Fix react-scripts in package.json (using sed for automation)
      sed -i 's/"react-scripts": "^0.0.0"/"react-scripts": "5.0.1"/' package.json
      npm install
    command: |
      # Start Frontend (npm start will typically expose port 3000)
      cd frontend
      npm start
